# Spring Actuator
# See https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
# Disable by default all but info

endpoints:
  enabled: false
  env:
    enabled: false
  pause:
    enabled: false
  resume:
    enabled: false
  info:
    enabled: true
    
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    
openlrs:
  # options - InMemoryStorage, RedisPubSubTierOneStorage, AwsKinesisTierOneStorage
  tierOneStorage: InMemoryStorage
  # options - InMemoryStorage, NoOpTierTwoStorage, NormalizedElasticsearchTierTwoStorage, 
  # NormalizedMongoTierTwoStorage, XApiOnlyElasticsearchTierTwoStorage, XApiOnlyAwsElasticsearchTierTwoStorage, NormalizedAwsElasticsearchTierTwoStorage
  tierTwoStorage: InMemoryStorage
  # options - PropertiesFileKeyManager,DatabaseKeyManager
  keyManager: DatabaseKeyManager
  
  
# values that MUST be set if openlrs.keyManager is set to: DatabaseKeyManager
# currently used by the pre-loader class to pre-populate db 
databasekeymanager:
  tenents:  
  # ID|Name|Consumerkey|Secret
    - 1|oauthkey1|key1|secret1
    - 2|oauthkey2|key2|secret2

#spring:
  # Redis
  # uncomment this line if you are using password protected redis
  #redis:
    #password: somepassword
    # uncomment these lines if you are using redis sentinel for HA
    #sentinel:
      #master: openlrsmaster
      #nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
  # For Elasticsearch or Mongo
  #data:
    #elasticsearch:
      #cluster-nodes: localhost:9300
  # For DatabaseKeyManager
  #datasource:
    #url: 
    #username: root
    #password: uni.dev
    #driver-class-name: com.mysql.jdbc.Driver
  #jpa:
    #hibernate:
      #ddl-auto: update
  
  
# AWS
aws:
  # AWS Elasticsearch service
  #es:
    #connectionUrl: https://search-something.us-east-1.es.amazonaws.com/
  # AWS Kinesis
  #kinesis:
    #endpoint: kinesis.us-east-1.amazonaws.com
    #stream: something
    

  